export enum Types {
  SET_FETCHING = 'SET_FETCHING',
  FETCH_LOAD_MORE_MOVIES_SUCCESS = 'FETCH_LOAD_MORE_MOVIES_SUCCESS',
  FETCH_LOAD_MORE_MOVIES_ERROR = 'FETCH_LOAD_MORE_MOVIES_ERROR',
  FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS',
  FETCH_MOVIES_ERROR = 'FETCH_MOVIES_ERROR'
}
